### ISSUE TITLE
关于6.6.1_CP

### ISSUE THREAD

**Issue by Ken-LiuL** [ctpbee/ctpbee#170]
请问下目前ctpbee_api使用的是6.6.1，如何使用6.6.1_cp 版本呢

**Comment by somewheve** [comment]
cp版本 ？ 啥意思

**Comment by somewheve** [comment]
穿透测试版本嘛 ？

**Comment by Ken-LiuL** [comment]
对的

**Comment by Ken-LiuL** [comment]
如果使用最新的ctpbee_api 是会报错api版本不一致的

**Comment by somewheve** [comment]
换下dll呗 ---- 回复的原邮件 ***@***.***>发送日期2022年03月02日 03:09 ***@***.***> ***@***.******@***.***>主题Re: [ctpbee/ctpbee] 关于6.6.1_CP (Issue #170)

如果使用最新的ctpbee_api 是会报错api版本不一致的



—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

You are receiving this because you commented.Message ID: ***@***.***>

[

{

***@***.***": "http://schema.org",

***@***.***": "EmailMessage",

"potentialAction": {

***@***.***": "ViewAction",

"target": "https://github.com/ctpbee/ctpbee/issues/170#issuecomment-1055767301",

"url": "https://github.com/ctpbee/ctpbee/issues/170#issuecomment-1055767301",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

***@***.***": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]
