### ISSUE TITLE
请问目前支持策略级别的持仓隔离吗

### ISSUE THREAD

**Issue by EricQAQ** [ctpbee/ctpbee#176]
请问目前支持策略级别的持仓隔离吗?

比如目前有2个策略同时在进行实盘, A策略和B策略都会交易jm这个品种, 此时A策略多开一手jm, B策略也多开一手, 期待的结果是在A策略中查询持仓, 显示jm持仓一手, B策略也是

**Comment by somewheve** [comment]
暂时没做支持 因为涉及到历史持仓 需要缓存历史持仓数据  这个方案我有点想写 但是还没头绪

**Comment by EricQAQ** [comment]
这个的思路感觉应该是自己维护持仓信息，忽略掉ctp返回的持仓信息，通过onrtntrade返回的成交数据来更新持仓，并做好持久化…

最近在找现成的解决方案，好像相关实现比较少…

**Comment by somewheve** [comment]
我目前主力还是在做策略的 这个持久化需要你自己实现了

**Comment by qtbgo** [comment]
请问这个策略持仓区分功能是不是已经实现了，在 https://github.com/ctpbee/ctpbee_tutorial/blob/master/modules/rec.md
里提到“为了ctpbee能够更好的适应环境，我们开发了策略持仓管理 基于场景，策略访问自己的持仓和策略访问其他策略的持仓”

**Comment by somewheve** [comment]
没有 这个没做完全 要等我有空才能写 ---- 回复的原邮件 ***@***.***>发送日期2022年04月26日 07:07 ***@***.***> ***@***.******@***.***>主题Re: [ctpbee/ctpbee] 请问目前支持策略级别的持仓隔离吗 (Issue #176)

请问这个策略持仓区分功能是不是已经实现了，在 https://github.com/ctpbee/ctpbee_tutorial/blob/master/modules/rec.md

里提到“为了ctpbee能够更好的适应环境，我们开发了策略持仓管理 基于场景，策略访问自己的持仓和策略访问其他策略的持仓”



—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

[

{

***@***.***": "http://schema.org",

***@***.***": "EmailMessage",

"potentialAction": {

***@***.***": "ViewAction",

"target": "https://github.com/ctpbee/ctpbee/issues/176#issuecomment-1109124004",

"url": "https://github.com/ctpbee/ctpbee/issues/176#issuecomment-1109124004",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

***@***.***": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by somewheve** [comment]
此项目标在1.6里面实现  先关闭了
