### ISSUE TITLE
（实盘）如果当前无持仓，是否不会调用策略的on_position逻辑

### ISSUE THREAD

**Issue by LJingnan** [ctpbee/ctpbee#197]
如题，我发现实盘时候，账户没有任何持仓时，策略的on_position没有反应

**Comment by somewheve** [comment]
这个逻辑是对的啊  一般情况下你是不需要处理on_position的 他是每秒自己查询的  要访问自己的仓位你需要使用 center去获取的

**Comment by LJingnan** [comment]
@somewheve  噢噢，原来是自己每秒查询。我去改写是因为：
1、我在开盘下组合单的时候，需要获取目前的持仓；
2、但是有可能我原来的账户并没有持仓，但也有可能有持仓。
3、我需要判断ctp是否已经给我返回了持仓，center获取这个方式，在ctp还没有返回持仓的时候，会给我返回一个空的list，
我没法判断这个空list，到底是我没有持仓还是ctp延迟还没给我返回持仓，所以我改写了position，加了一个mark标志去判断
到底是哪种情况。

**Comment by somewheve** [comment]
有一个on_init方法 那个就是查询ok了才会触发的

jingnan ***@***.***> 于2022年7月9日周六 00:38写道：

**Comment by LJingnan** [comment]
@somewheve 哦哦，意思是我的开盘组合单放在init里面写就能保证self.center.position拿到的是真实持仓，而不会导致有时候position还没返回

**Comment by somewheve** [comment]
on_init触发就说明仓位初始化ok啦---- 回复的原邮件 ***@***.***>发送日期2022年07月09日 09:33 ***@***.***> ***@***.******@***.***>主题Re: [ctpbee/ctpbee] （实盘）如果当前无持仓，是否不会调用策略的on_position逻辑 (Issue #197)

@somewheve 哦哦，意思是我的开盘组合单放在init里面写就能保证self.center.position拿到的是真实持仓，而不会导致有时候position还没返回



—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

[

{

***@***.***": "http://schema.org",

***@***.***": "EmailMessage",

"potentialAction": {

***@***.***": "ViewAction",

"target": "https://github.com/ctpbee/ctpbee/issues/197#issuecomment-1179454938",

"url": "https://github.com/ctpbee/ctpbee/issues/197#issuecomment-1179454938",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

***@***.***": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by LJingnan** [comment]
@somewheve 嗯，那我把组合单放在on_init好了，因为之前我是给app写了个下组合单的函数，我直接start之后马上运行这个方法，结果其实on_init还没运行就下出去了

**Comment by somewheve** [comment]
嗯嗯

jingnan ***@***.***> 于2022年7月10日周日 10:37写道：

**Comment by LJingnan** [comment]
好像不太对，我在on_init里面设置了一个标志
```
    def on_init(self, init: bool) -> None:
        self.app.mark_on_init = 1
        print(f"!!!!!!!!!! init :{init}")
```
结果我发现运行顺序是这样的：
![image](https://user-images.githubusercontent.com/43166853/178174899-c1e8c246-2b70-487e-9802-65e0ee6413dc.png)
说明是先拿到了position，过了一段时间才去on_init

**Comment by somewheve** [comment]
都说了 on_init是确保拿到仓位之后再触发的  你在on_init里面通过 self.center去拿本地仓位不就好了

**Comment by LJingnan** [comment]
嗯嗯~多谢。我只是在想有没有更快的办法，中间有延迟，不过也能解决了，多谢！
