### ISSUE TITLE
TickData结构里面缺少成交金额

### ISSUE THREAD

**Issue by LJingnan** [ctpbee/ctpbee#205]
我看文档介绍，TickData好像是没有成交金额，但是我看CTP的c++文件里面是有成交金额这一字段的，请问是为什么？
	///数量
	TThostFtdcVolumeType	Volume;
	///成交金额
	TThostFtdcMoneyType	Turnover;

**Comment by somewheve** [comment]
有turnover字段的 你看下---- 回复的原邮件 ***@***.***>发送日期2022年09月25日 16:51 ***@***.***> ***@***.***>主题[ctpbee/ctpbee] TickData结构里面缺少成交金额 (Issue #205)

我看文档介绍，TickData好像是没有成交金额，但是我看CTP的c++文件里面是有成交金额这一字段的，请问是为什么？

///数量

TThostFtdcVolumeType	Volume;

///成交金额

TThostFtdcMoneyType	Turnover;



—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

[

{

***@***.***": "http://schema.org",

***@***.***": "EmailMessage",

"potentialAction": {

***@***.***": "ViewAction",

"target": "https://github.com/ctpbee/ctpbee/issues/205",

"url": "https://github.com/ctpbee/ctpbee/issues/205",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

***@***.***": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by LJingnan** [comment]
哦哦,那可能是文档漏了
![image](https://user-images.githubusercontent.com/43166853/192272981-8913ef48-2f02-45a2-a2d2-a1db6e09160c.png)

**Comment by somewheve** [comment]
已经提交修复 
https://github.com/ctpbee/ctpbee_tutorial/commit/b7c7ec26ef4dc081c9e89dd5cff0b16de6128ef6
